### PR TITLE
Retina icon

### PR DESCRIPTION
**Pull request by pluwen**
256*256

### CODE REVIEW

**Comment by rjoydip** [comment]
What's wrong with existing one ?. LGTM

**Comment by pluwen** [comment]
I make an big icon for you, just the same look, but more bigger, more cleaner.

**Comment by rjoydip** [comment]
Okay. Thanks for this PR 💓

**Comment by pluwen** [comment]
image
More clear now~

**Comment by rjoydip** [comment]
👍

**Pull request merged**
