### PR TITLE
Feat: Live editing with live server

### LINKED ISSUE #119: Trully live?
I'd like to ask you about functionality of your product. So using your product I need to save my file when I want to see any changes. Is it possible for you to make your product more similar to Bracket's live preview where I see changes instantly when I edit document I work with. That functionality lets see changes without affecting original file.

### PR DESCRIPTION
**Pull request by rjoydip**
Fixed #119, #71 

## Description

Live editing works with `liveServer.settings.liveEditing` configuration with `liveServer.experimental.liveEditing` flag.

### CODE REVIEW

**Comment by ritwickdey** [comment]
Live editing?

**Comment by rjoydip** [comment]
Yes. Live html editing when a edits html file from vscode. But live server will works as expected.

**Comment by ritwickdey** [comment]
Sounds great...!! Is this in working stage? Can I test it now?

**Comment by rjoydip** [comment]
Yes you can test. But i didn't test with svg and custom component.

**Comment by Dob6458** [comment]
Nice project :-)

**Comment by Dob6458** [comment]
@rjoydip you can follow me on profile please, https://github.com/Dob6458 and click "Follow". :-)

**Comment by ritwickdey** [comment]
Though it has few bugs but it is working like a charm. It is really impressive idea.

**Comment by ritwickdey** [comment]
Suppose I'm editing `Index.html` and now I move to `foo.html` & start typing in vscode but `index.html` is opened in the browser. In this scenario, the content of `foo.html` is showing on `Index.html` page in the browser.

**Comment by rjoydip** [comment]
let me know those bugs. If it possible to me then I will fix those.

**Comment by rjoydip** [comment]
Yes, that's a good idea. Go ahead.

**Comment by rjoydip** [comment]
closed due to some technical problem

**Pull request closed without merging**
