### PR TITLE
Fallback to random port if the default is taken.

### PR DESCRIPTION
**Pull request by Almo7aya**
## PR Type

What kind of change does this PR introduce?

```html
[ ] Bugfix
[x] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other: <!-- Please describe: -->
```

## What is the current behavior?

Issue Number: #328 

## What is the new behavior?

Describe in issue: #328 

## Does this PR introduce a breaking change?

```text
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Almo7aya** [comment]
Will you review this PR?

**Comment by nash-ye** [comment]
Please, response to @Almo7aya . :+1:

**Comment by lilililee** [comment]
if set port again and again， does this PR can work as well？ it seems can adjust port only once.

**Comment by Almo7aya** [comment]
@lilililee It will 5500 `++` until it finds an open port!

**Comment by lilililee** [comment]
@Almo7aya Nice!👍 Full of expectation it release~

**Comment by ritwickdey** [comment]
I'm feeling seriously sorry when I this PR. Really awesome work!! :cupid:

**Pull request merged**
