### PR TITLE
[Bug]: updated grammar in appModel.ts

### PR DESCRIPTION
**Pull request by Jacobkyalo**
###correcting grammar

### CODE REVIEW

**Comment by ritwickdey** [comment]
Off topic: are you facing `Something is went wrong! Please check into Developer Console or report on GitHub` error ?

**Comment by Apt41Kira** [comment]
print(f"{attempt[0]}:{attempt[1]}")

**Comment by prechayimmee** [comment]
#2846

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Need help

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Thanks

**Review by krsjenswbp — COMMENTED** [review]
add

**Pull request merged**
